variables:
  IMAGE_VERSION: "1.3.3"

stages:
  - prepare-docker

express:
  image: docker:latest
  stage: prepare-docker
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
    - docker pull mauromazzocchetti/webtorrent-express-api:latest
    - docker build --progress=plain --tag="mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION" --tag="mauromazzocchetti/webtorrent-express-api:latest" ./
    - docker push mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION
    - docker push mauromazzocchetti/webtorrent-express-api:latest
    - docker logout
  only:
    - master
