variables:
  IMAGE_VERSION: "1.3.6"
  GIT_DEPTH: '3'
  SIMPLECOV: 'true'
  RUST_BACKTRACE: '1'
  RUSTFLAGS: ''
  CARGOFLAGS: ''

stages:
  - build
  - build-linux
  - build-mac
  - build-win


cache:
  key: '${CI_COMMIT_BRANCH}'
  paths:
    - node_modules/

express:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
    - docker pull mauromazzocchetti/webtorrent-express-api:latest
    - docker build --progress=plain --tag="mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION" --tag="mauromazzocchetti/webtorrent-express-api:latest" ./
    - docker push mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION
    - docker push mauromazzocchetti/webtorrent-express-api:latest
    - docker logout
  only:
    - main


linux-build:
  stage: build-linux
  image: node:16
  script:
    - npm i node-pre-gyp
    - npm install
    - npm run bundle-linux
  artifacts:
    expire_in: 1 week
    paths:
      - 'dist/*.AppImage'
      - 'dist/*.tar.xz'
      - 'dist/*.snap'
      - 'dist/*.deb'
  only:
    - feature-build

osx-build:
  stage: build-mac
  script:
    - npm i node-pre-gyp
    - npm install
    - npm run bundle-mac
  tags:
    - darwin-shell
  artifacts:
    expire_in: 1 week
    paths:
      - 'dist/*.dmg'
      - 'dist/*.zip'
  only:
    - feature-build

win-build:
  stage: build-win
  image: electronuserland/builder:16-wine
  script:
    - npm i node-pre-gyp
    - npm install
    - npm run bundle-win
  artifacts:
    expire_in: 1 week
    paths:
      - 'dist/*.exe'
  only:
    - feature-build
