variables:
  DOCKER_USERNAME: "mauromazzocchetti"
  DOCKER_PASSWORD: "F-C6dD!i3cKaiM-"
  IMAGE_VERSION: "0.5"

stages:
  - prepare-docker

express:
  image: docker:latest
  stage: prepare-docker
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
    - docker build --progress=plain --tag="mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION" ./
    - docker push mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION
    - docker logout
