variables:
  IMAGE_VERSION: "1.0"

stages:
  - prepare-docker

web:
  image: node:16.8.0
  stage: prepare-docker
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - git clone https://gitlab.com/t5257/webtorrent-web-gui-standalone.git
    - cd webtorrent-web-gui-standalone/
    - npm i
    - npm run build-local
    - cp -R build ../public/
    - cd ..
    - rm -rf webtorrent-web-gui-standalone/
    - npm install -g node-pre-gyp
    - npm install -g pkg
    - npm i
    - npm run bundle
  artifacts:
    paths:
      - build/

express:
  image: docker:latest
  stage: prepare-docker
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
    - docker pull mauromazzocchetti/webtorrent-express-api:latest
    - docker build --progress=plain --tag="mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION" --tag="mauromazzocchetti/webtorrent-express-api:latest" ./
    - docker push mauromazzocchetti/webtorrent-express-api:$IMAGE_VERSION
    - docker push mauromazzocchetti/webtorrent-express-api:latest
    - docker logout
